import {
  Box,
  Card,
  Grid,
  CardActionArea,
  CardMedia,
  CardContent,
  Typography,
  CardActions,
  Button,
} from '@mui/material';
import Head from 'next/head';
import Layout from '../../src/components/Layout';
import Product from '../../src/models/Product';
import dbConnect from '../../utils/dbConnect';
import Image from 'next/image';

export default function Products({ products }) {
  return (
    <Layout>
      <Head>
        <title>Arion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          p: 1,
        }}
      >
        <h2>Products</h2>
      </Box>

      <Grid
        container
        spacing={2}
        sx={{
          p: 3,
        }}
      >
        {products.map((product) => (
          <Grid
            item
            md={3}
            key={product._id}
            sx={{
              flexGrow: 1,
            }}
          >
            <Card>
              <CardActionArea>
                <CardMedia
                  component="img"
                  height="140"
                  image={product.imageUrl}
                  title={product.name}
                ></CardMedia>
                <CardContent>
                  <Typography>{product.name}</Typography>
                </CardContent>
              </CardActionArea>
              <CardActions>
                <Typography>${product.sellingPrice}</Typography>
                <Button size="small" color="primary">
                  Add to Cart
                </Button>
              </CardActions>
            </Card>
          </Grid>
        ))}
      </Grid>
    </Layout>
  );
}
export async function getServerSideProps() {
  await dbConnect.connect();
  const products = await Product.find({}).lean();
  // const products = await axios.get('http://localhost:3000/api/products/');

  await dbConnect.disconnect();

  return {
    props: {
      products: products.map(dbConnect.convertDocToObj),
    },
  };
}
