import { Container, Grid } from '@mui/material';
import axios from 'axios';
import Head from 'next/head';
import Layout from '../../src/components/Layout';
import Product from '../../src/models/Product';
import dbConnect from '../../utils/dbConnect';

export default function Products({ products }) {
  return (
    <Layout>
      <Head>
        <title>Arion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Products</h2>
      <Container>
        {products.map((product) => (
          <div key={product._id}>{product.name}</div>
        ))}
      </Container>
    </Layout>
  );
}
export async function getServerSideProps() {
  await dbConnect.connect();
  const products = await Product.find({}).lean();
  // const products = await axios.get('http://localhost:3000/api/products/');

  await dbConnect.disconnect();

  return {
    props: {
      products: products.map(dbConnect.convertDocToObj),
    },
  };
}
