import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      firstName: 'Sam',
      lastName: 'Doe',
      mobile: '+254700000000',
      email: 'sam@gmail.com',
      password: bcrypt.hashSync('jitters'),
      isAdmin: false,
      // isActive: true,
      // email_confirmed: true,
    },
    {
      firstName: 'Admin',
      lastName: 'System',
      mobile: '+254700000001',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('jitters'),
      isAdmin: true,
      // isActive: true,
      // email_confirmed: true,
    },
  ],
  products: [
    {
      sku: 'XB7655',
      name: 'X-Box',
      slug: 'x-box',
      description: '64GB RAM 24 inch',
      productCategory: 'Electronics',
      productType: 'Computer Game',
      brand: 'Sony',
      buyingPrice: 189.99,
      sellingPrice: 199.99,
      countInStock: 5,
      taxRate: 0.16,
      productDiscountRate: 0,
      imageUrl: '/images/products/xbox.jpg',
      rating: 3.5,
      numReviews: 4,
    },
    {
      sku: 'FCXE954',
      name: 'iMac Computer',
      slug: 'imac-computer',
      description: 'Core i7 1TB HD, 64GB RAM 24 inch',
      productCategory: 'Electronics',
      productType: 'Computer',
      brand: 'Apple',
      buyingPrice: 456.87,
      sellingPrice: 510.5,
      countInStock: 5,
      taxRate: 0.16,
      productDiscountRate: 0.1,
      imageUrl: '/images/products/computer.jpg',
      rating: 4.7,
      numReviews: 13,
    },
    {
      sku: 'FRD0954',
      name: 'Laptop Computer',
      slug: 'laptop-computer',
      description: 'Core i7 1TB HD, 64GB RAM 24 inch',
      productCategory: 'Electronics',
      productType: 'Laptop Computer',
      brand: 'Apple',
      buyingPrice: 327.68,
      sellingPrice: 331.89,
      countInStock: 7,
      taxRate: 0.16,
      productDiscountRate: 0,
      imageUrl: '/images/products/laptop.jpg',
      rating: 3.7,
      numReviews: 8,
    },
    {
      sku: 'FRD7865',
      name: 'Smart TV',
      slug: 'smart-tv',
      description: 'Bluetooth, 30 GB internal drive',
      productCategory: 'Electronics',
      productType: 'Smart Television',
      brand: 'Generic',
      buyingPrice: 467.89,
      sellingPrice: 489.99,
      countInStock: 13,
      taxRate: 0.16,
      productDiscountRate: 0,
      imageUrl: '/images/products/smart-tv.png',
      rating: 2.9,
      numReviews: 3,
    },
    {
      sku: 'FRD7454',
      name: 'Classic Watch',
      slug: 'classic-watch',
      description: 'Wrist Watch',
      productCategory: 'Electronics',
      productType: 'Wrist Watch',
      brand: 'Generic',
      buyingPrice: 123.65,
      sellingPrice: 133.95,
      countInStock: 2,
      taxRate: 0,
      productDiscountRate: 0,
      imageUrl: '/images/products/watch.jpg',
      rating: 3.5,
      numReviews: 4,
    },
  ],
};

export default data;
