import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      firstName: 'Sam',
      lastName: 'Doe',
      mobile: '+254700000000',
      email: 'sam@example.com',
      password: bcrypt.hashSync('password.123'),
      avatar: 'images/users/sam.png',
      isAdmin: false,
      isActive: true,
      email_confirmed: true,
    },
    {
      firstName: 'Admin',
      lastName: 'System',
      mobile: '+254700000001',
      email: 'admin@example.com',
      password: bcrypt.hashSync('password.123'),
      avatar: 'images/users/admin.png',
      isAdmin: true,
      isActive: true,
      email_confirmed: true,
    },
    {
      firstName: 'Jane',
      lastName: 'Doe',
      mobile: '+254700000002',
      email: 'janedoe@example.com',
      password: bcrypt.hashSync('password.123'),
      avatar: 'images/users/jane.png',
      isAdmin: false,
      isActive: false,
      email_confirmed: false,
    },
  ],
  products: [
    {
      sku: 'XB7655',
      name: 'X-Box',
      slug: 'x-box',
      description: '64GB RAM 24 inch',
      productCategory: 'Electronics',
      productType: 'Computer Game',
      brand: 'Sony',
      buyingPrice: 21000,
      sellingPrice: 24000,
      countInStock: 5,
      taxRate: 0.16,
      imageUrl: '/images/products/xbox.jpg',
      rating: 3.5,
      numReviews: 4,
    },
    {
      sku: 'FCXE954',
      name: 'iMac Computer',
      slug: 'imac-computer',
      description: 'Core i7 1TB HD, 64GB RAM 24 inch',
      productCategory: 'Electronics',
      productType: 'Computer',
      brand: 'Apple',
      buyingPrice: 90000,
      sellingPrice: 100000,
      countInStock: 5,
      taxRate: 0.16,
      imageUrl: '/images/products/computer.jpg',
      rating: 4.7,
      numReviews: 13,
    },
    {
      sku: 'FRD0954',
      name: 'Laptop Computer',
      slug: 'laptop-computer',
      description: 'Core i7 1TB HD, 64GB RAM 24 inch',
      productCategory: 'Electronics',
      productType: 'Laptop Computer',
      brand: 'Apple',
      buyingPrice: 60000,
      sellingPrice: 70000,
      countInStock: 25,
      taxRate: 0.16,
      imageUrl: '/images/products/laptop.jpg',
      rating: 3.7,
      numReviews: 8,
    },
    {
      sku: 'FRD7865',
      name: 'Smart TV',
      slug: 'smart-tv',
      description: 'Bluetooth, 30 GB internal drive',
      productCategory: 'Electronics',
      productType: 'Smart Television',
      brand: 'Generic',
      buyingPrice: 15000,
      sellingPrice: 16000,
      countInStock: 13,
      taxRate: 0.16,
      imageUrl: '/images/products/smart-tv.png',
      rating: 2.9,
      numReviews: 3,
    },
    {
      sku: 'FRD7454',
      name: 'Classic Watch',
      slug: 'classic-watch',
      description: 'Wrist Watch',
      productCategory: 'Electronics',
      productType: 'Wrist Watch',
      brand: 'Generic',
      buyingPrice: 9000,
      sellingPrice: 11000,
      countInStock: 2,
      taxRate: 0.16,
      imageUrl: '/images/products/watch.jpg',
      rating: 3.5,
      numReviews: 4,
    },
  ],
};

export default data;
